services:
  - type: web
    name: stock-prediction
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    runtime: python
    pythonVersion: 3.10.13
